In [ ]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

In [1]:
import torch
import numpy as np


In [6]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
# x_data
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# x_np
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data,dtype=torch.float)
x_rand

tensor([[0.2601, 0.9986],
        [0.4002, 0.2287]])

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.9067, 0.6177, 0.4922],
        [0.6663, 0.0134, 0.3808]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [9]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [12]:
print(tensor.shape)
print(tensor.dtype)
print(tensor)

torch.Size([3, 4])
torch.float32
tensor([[0.2915, 0.9390, 0.8166, 0.5853],
        [0.9096, 0.0047, 0.1320, 0.7740],
        [0.5951, 0.1125, 0.3761, 0.4372]])


In [15]:
tensor = torch.ones(4,3)
print(tensor)
print(tensor[0])
print(tensor[:,0])
print(tensor[...,-1])
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [16]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.]])


In [19]:
print(tensor)
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[0.4305, 0.5944, 0.5610, 0.3067],
        [0.6524, 0.3941, 0.5982, 0.8897],
        [0.4182, 0.3080, 0.3249, 0.6694],
        [0.5735, 0.5791, 0.5156, 0.7866]])


tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [21]:
z1 = tensor*tensor
z2 = tensor.mul(tensor)
print(z1,z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]]) tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])

In [22]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item)
print(type(agg_item))

tensor(8.)
8.0
<class 'float'>


In [23]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6.],
        [6., 5., 6.],
        [6., 5., 6.],
        [6., 5., 6.]])


In [24]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [27]:
t.add_(1)
print(t)
print(n)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [28]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out=n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
